### ISSUE TITLE
Beat ya to it lol

### ISSUE THREAD

**Issue by MistressPlague** [xKiraiChan/WingAPI#1]

**Comment by xKiraiChan** [comment]
I never thought to check your repositories, I heard @loukylor and @arion-kun were making their own but it wasn't out by the time I had made it.
Which repo is yours in? I cannot seem to find it.

**Comment by JustArion** [comment]
aaaaaaaaaaaa it sends an email when im tagged

**Comment by JustArion** [comment]
i have the pain of doing it from scratch, not cloning a prefab

**Comment by MistressPlague** [comment]
I even used the original transitions by reversing how they were handling menus lol
It's on my PlagueVRC org acc if y'all want to have fun with it. Feel free to contribute too; let's get mods going for beta.

**Comment by MistressPlague** [comment]
https://github.com/PlagueVRC/PlagueButtonAPI/tree/beta-ui

**Comment by xKiraiChan** [comment]
My only problem with your design is you have the source file duplicated per mod.
In my opinion it would be better to have a single copy of it and everything references it

**Comment by MistressPlague** [comment]
It's a .dll. Already done that. Make sure you're on the beta-ui branch.

**Comment by MistressPlague** [comment]
https://github.com/PlagueVRC/PlagueButtonAPI/actions?query=event%3Apush+is%3Asuccess for the latest release files

**Comment by MistressPlague** [comment]
You're also free to hop in the buttonapi discord so talking is easier, as here might annoy peeps with emails.

**Comment by xKiraiChan** [comment]
Alright. 
As for the future of this repository, I'll probably make it reference yours and add features onto it such as a reflective API.

**Comment by MistressPlague** [comment]
Discord link is on the repo lol
Let's get this shi going
